home/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^search/$', views.search, name='search'),
    url(r'^reservate/', views.reservate_calendar),
    url(r'^(?P<room_id>[0-9]+)/booking/(?P<book_id>[0-9]+)/delete/$', views.delete_calendar)
]

magma/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from home import views
from django.contrib.auth import views as auth_views


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^rooms/', include('room.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^login/', auth_views.LoginView.as_view(), name='login'),
    url(r'^accounts/', include('registration.backends.model_activation.urls')),
    url(r'', views.Home.as_view(), name='home'),
]

home/models.py
from django.db import models

# Create your models here.

room/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User


class Room(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Booking(models.Model):
    start = models.DateTimeField()
    end = models.DateTimeField(null=True, blank=True)
    title = models.CharField(max_length=255)
    start_time = models.TimeField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)
    room = models.ForeignKey(Room)
    user = models.ForeignKey(User)

    def __str__(self):
        return self.title


# class Bill(models.Model):
#     user = models.ForeignKey(User)
#     room = models.ForeignKey(Room)
#     booking = models.ForeignKey(Booking)
#     date = models.DateTimeField(auto_now_add=True)
#     subtotal = models.DecimalField(default=0.0, max_digits=10, decimal_places=2)
#     total = models.DecimalField(default=0.0, max_digits=10, decimal_places=2)


class Image(models.Model):
    room = models.ForeignKey(Room)
    image = models.ImageField(upload_to='rooms/images/')

    def __unicode__(self):
        return str(self.image)


class Features(models.Model):
    room = models.OneToOneField(Room)
    slate = models.BooleanField(default=False)
    spotlight = models.BooleanField(default=False)
    capacity = models.IntegerField(default=0)
    chairs = models.IntegerField(default=0)
    wifi = models.BooleanField(default=False)
    sound_system = models.BooleanField(default=False)
    videoConference_equipament = models.BooleanField(default=False)

    def __str__(self):
        return self.room.name

home/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from rest_framework.utils import json

from room.models import Booking, Room
from django.views.generic import ListView
from room.views import dates


class Home(ListView):
    model = Room
    context_object_name = 'rooms'
    template_name = 'home.html'


def search(request):
    # import pdb; pdb.set_trace()

    if request.POST['date']:
        search_date = {
            'date': request.POST['date'],
            'hours': request.POST['hours']
        }
        time = search_date['date'] + " 00:00:00"
        time = datetime.strptime(time, "%Y-%m-%d %H:%M:%S")
        if time > datetime.today():
            if search_date['hours']:
                time = search_date['date'] + " " + search_date['hours'] + ":00"
                time = datetime.strptime(time, "%Y-%m-%d %H:%M:%S")
                rooms = Room.objects.exclude(booking__start=time)
            else:
                rooms = Room.objects.exclude(booking__start=search_date['date'], booking__end=search_date['date'])
        else:
            return redirect('home')
    else:
        return redirect('home')

    return render(request, 'home.html', {'date': time.strftime("%d-%m-%Y %H:%M"), 'rooms': rooms})


@login_required
def reservate_calendar(request):
    response_data = {}
    start_time = request.POST['start_time']
    end_time = request.POST['end_time']
    date_entry = dates(start_time, request.POST['start'], False)
    date_today = datetime.today()
    if datetime.strftime(date_entry, "%Y-%m-%d %H:%M:%S") > datetime.strftime(date_today, "%Y-%m-%d %H:%M:%S"):
        if start_time:
            if start_time < end_time:
                date_depature = dates(end_time, request.POST['start'])
                date_entry = dates(start_time, request.POST['start'])
                if request.POST['room'] != 'select':
                    room = get_object_or_404(Room, pk=request.POST['room'])
                    if Booking.objects.filter(room=room, start__lte=date_entry,
                                              end__gte=date_depature).exists():
                        response_data['error'] = 'La reserva ya existe en este tramo horario'
                    else:
                        r = Booking(title=request.POST['title'], start=date_entry, end=date_depature, start_time=start_time,
                                    end_time=end_time, room=room, user=request.user)
                        r.save()

                        response_data['result'] = 'Se ha creado la reserva'
                else:
                    response_data['error'] = "Debes seleccionar una sala"
            else:
                response_data['error'] = "La hora de salida debe ser mayor a la de entrada"

        else:
            response_data['error'] = 'Debes seleccionar una hora'
    else:
        response_data['error'] = 'Debes seleccionar una fecha valida'
    return HttpResponse(json.dumps(response_data), content_type="application/json")


@login_required
def delete_calendar(request, room_id, book_id):

    user_id = request.GET['user']
    response_data = {}
    if Booking.objects.filter(room_id=room_id, id=book_id, user_id=user_id).exists():
        Booking.objects.filter(room_id=room_id, id=book_id, user_id=user_id).delete()
        response_data['result'] = 'Evento Eliminado Correctamente'
    else:
        response_data['error'] = 'El evento no esta asociado a este usuario'

    return HttpResponse(json.dumps(response_data), content_type="application/json")

templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <title>{% block title %}User test{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>
    <div id="header">
        {% block header %}
	<a href="{% url 'home' %}">{% trans "Home" %}</a> |

	{% if user.is_authenticated %}
	{% trans "Logged in" %}: {{ user.username }}
	(<a href="{% url 'auth_logout' %}">{% trans "Log out" %}</a> |
	<a href="{% url 'auth_password_change' %}">{% trans "Change password" %}</a>)
	{% else %}
	<a href="{% url 'auth_login' %}">{% trans "Log in" %}</a>
	{% endif %}
	<hr />
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <div id="footer">
        {% block footer %}
        <hr />
        {% endblock %}
    </div>


<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

templates/home.html
{% extends 'layout.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" href="{% static 'css/fullcalendar.min.css' %}">

{% endblock %}
{% block nav %}
    {% include 'includes/nav.html' %}
    <div class="container-fluid d-flex flex-column justify-content-md-center align-content-md-center  div-nav">
        <div class="container p-5 m-5  ">
            <h2 class="text-white d-flex flex-row justify-content-center">Reserve your space to start working</h2>
            <section class="d-flex flex-row justify-content-md-center">
                <form class="form-inline " action="{% url 'search' %}" method="post" id="form-reservate">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="text-white" for="date">Day</label>
                        <input type="date" class="form-control" name="date" id="date">
                    </div>
                    <div class="form-group">
                        <label class="text-white" for="hours">Time Entry</label>
                        <input type="time" class="form-control" name="hours" id="hours">
                    </div>
                    <button class="btn btn-info ml-3">Search</button>
                </form>
                {% if context %}
                    <p class="text-danger">{{ context }}</p>
                {% endif %}
            </section>

        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container-fluid pt-5 bg-light ">
        <div class="row h-100">
            {% if date %}
                <div class="container-fluid w-100 mb-4 p-2" style="background-color: rgba(104,180,178,0.26)">
                    <p class="h6 text-center"><strong>{{ rooms.count }}</strong> salas disponibles el
                        <strong>{{ date }}</strong></p>
                </div>
            {% endif %}
            {% for room in rooms %}
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3 pb-4  pt-md-3   d-flex flex-row justify-content-center align-content-center"
                     id="card-home">
                    <div class="col">
                        <div class="card" style="width: 18rem;">
                            <div id="carousel{{ room.name }}" class="carousel slide" data-ride="carousel">
                                <ol class="carousel-indicators">
                                    {% for image in room.image_set.all %}
                                        <li data-target="#carousel{{ room.name }}Indicators"
                                            data-slide-to="{{ forloop.counter }}"
                                            {% if forloop.first %}class="active"{% endif %}></li>
                                    {% endfor %}
                                </ol>
                                <div class="carousel-inner">
                                    {% for image in room.image_set.all %}
                                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                            <img class="d-block w-100"
                                                 src="{% static image %}" width="200" height="200" alt="First slide">
                                        </div>
                                    {% endfor %}
                                </div>
                                <a class="carousel-control-prev" href="#carousel{{ room.name }}" role="button"
                                   data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carousel{{ room.name }}" role="button"
                                   data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
                            <div class="card-body">
                                <p class="card-text text-center">{{ room.name }}</p>
                                <p>{{ room.description }}</p>
                            </div>
                            <div class="card-footer">
                                <a href="{% url 'reservation' room_id=room.id %}" class="btn btn-primary">Reservate</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-11  m-5 p-5">
            <div id="calendar"></div>
        </div>
        <hr class="container" style="border: 1px solid burlywood">
        <div class="container  d-flex flex-row">

            <div class="col-4 m-2  border">
                <h4 class="text-center">Philosophy</h4>
                <p class="text-muted text-capitalize">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac mauris vel ligula dictum luctus.
                    Nam libero tellus, mollis ut justo non, efficitur vestibulum mauris. Morbi sed maximus quam.
                    Praesent convallis, nisl vitae elementum condimentum, ex purus bibendum neque, ut vehicula augue
                    purus sed ex
                </p>
            </div>
            <div class="col-4 m-2 border">
                <h4 class="text-center">Way Of Working</h4>
                <p class="text-muted text-capitalize">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac mauris vel ligula dictum luctus.
                    Nam libero tellus, mollis ut justo non, efficitur vestibulum mauris. Morbi sed maximus quam.
                    Praesent convallis, nisl vitae elementum condimentum, ex purus bibendum neque, ut vehicula augue
                    purus sed ex
                </p>
            </div>
            <div class="col-4 m-2 border">
                <h4 class="text-center">Team</h4>
                <p class="text-muted text-capitalize">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac mauris vel ligula dictum luctus.
                    Nam libero tellus, mollis ut justo non, efficitur vestibulum mauris. Morbi sed maximus quam.
                    Praesent convallis, nisl vitae elementum condimentum, ex purus bibendum neque, ut vehicula augue
                    purus sed ex
                </p>
            </div>
        </div>
    </div>
    <input type="hidden" value="{{ user.id }}" id="idUser">
    {% include 'includes/bootstrap_modal_event.html' %}
    {% include 'includes/bootstrap_modal_addEvent.html' %}
{% endblock %}

{% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="{% static 'js/calendarHome.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Magma Site{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
          integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>
{% block nav %}
    {% include 'includes/nav.html' %}
{% endblock %}
{% block content %}

{% endblock %}
<footer class=" h-100 pt-5 mt-5 footer-top ">
    <div class="col pb-5 ">
        <div class="container col-6">
            <ul class="navbar-nav ml-auto d-flex flex-row justify-content-between">
                <li class="text-white list-nav-li nav-item  text-muted"><a href="#">Contact</a></li>
                <li class="text-white list-nav-li nav-item  text-muted">*</li>
                <li class="text-white list-nav-li nav-item  text-muted"><a href="#">Web Site</a></li>
                <li class="text-white list-nav-li nav-item  text-muted ">*</li>
                <li class="text-white list-nav-li nav-item  text-muted"><a href="#">Magma</a></li>
            </ul>
        </div>
    </div>
    <div class="col bg-dark">
        <div class="container ">
            <ul class="navbar-nav ml-auto d-flex flex-row justify-content-around">
                <li class=" list-nav-li nav-item "><a href="https://twitter.com/wearecommite"><i class="fab fa-twitter fa-2x"></i></a></li>
                <li class="list-nav-li nav-item"><a  href=""><i class="fab fa-instagram fa-2x"></i></a></li>
            </ul>
        </div>
    </div>
</footer>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/fullcalendar.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block js %}
{% endblock %}
</body>
</html>

templates/reservate.html
{% extends 'layout.html' %}
{% load static %}
{% load widget_tweaks %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'css/fullcalendar.min.css' %}">
{% endblock %}
{% block content %}
    <div class="container bg-light">
        <div class="row mt-5">
            <div class="col-8 h-100 pt-4">
                <div class="container">
                    <h4 class="text-capitalize text-left p-2">{{ room.name }} <br>
                        <small class="text-muted">Texto Texto Texto Texto</small>
                    </h4>
                    <div id="carousel{{ room.name }}" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            {% for image in room.image_set.all %}
                            <li data-target="#carousel{{ room.name }}Indicators" data-slide-to="{{ forloop.counter }}" {% if forloop.first %}class="active"{% endif %}></li>
                            {% endfor %}
                        </ol>
                        <div class="carousel-inner">
                            {% for image in room.image_set.all %}
                            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                <img class="d-block w-100"
                                     src="{% static image  %}" alt="First slide">
                            </div>
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#carousel{{ room.name }}" role="button"
                           data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carousel{{ room.name }}" role="button"
                           data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>

                    <div class="accordion pt-3" id="accordion">
                        <div class="card">
                            <div class="card-header" id="headingOne">
                                <h5 class="mb-0">
                                    <button class="btn w-100 text-left" type="button" data-toggle="collapse"
                                            data-target="#collapseDescription" aria-expanded="true"
                                            aria-controls="collapseDescription">
                                        <i class="fas fa-align-left"></i> <strong>Description</strong>
                                    </button>
                                </h5>
                            </div>

                            <div id="collapseDescription" class="collapse show" aria-labelledby="headingOne"
                                 data-parent="#accordion">
                                <div class="card-body">
                                    {{ room.description }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="accordion pt-3" id="accordion">
                        <div class="card">
                            <div class="card-header" id="headingOne">
                                <h5 class="mb-0">
                                    <button class="btn w-100 text-left" type="button" data-toggle="collapse"
                                            data-target="#collapseDetailed" aria-expanded="true"
                                            aria-controls="collapseDetailed">
                                        <i class="fas fa-bookmark"></i> <strong>Detailed information</strong>
                                    </button>
                                </h5>
                            </div>

                            <div id="collapseDetailed" class="collapse show" aria-labelledby="headingOne"
                                 data-parent="#accordion">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col">
                                            <div class="row pl-3">
                                                <i class="fas fa-info-circle"></i> <h5 class="text-center pl-2"> Details</h5>
                                            </div>
                                            <ul class="list-group">
                                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                                    Capacity
                                                    <span class="badge badge-pill badge-primary">{{ room.features.capacity }}</span>
                                                </li>
                                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                                    Chairs
                                                   <span class="badge badge-pill badge-primary">{{ room.features.chairs }}</span>
                                                </li>
                                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                                    Slate
                                                  {% if room.features.slate == 1 %}
                                                      <span><i class=" far fa-check-circle"></i></span>
                                                    {% else %}
                                                    <span><i class="far fa-times-circle"></i></span>
                                                    {% endif %}
                                                </li>

                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                                    Wifi
                                                  {% if room.features.wifi == 1 %}
                                                      <span><i class="far fa-check-circle"></i></span>
                                                    {% else %}
                                                    <span><i class="far fa-times-circle"></i></span>
                                                    {% endif %}
                                                </li>

                                            </ul>
                                        </div>
                                        <div class="col">
                                            <div class="row pl-3 ">
                                                <i class="fas fa-plug"></i><h5 class="text-center pl-2">Technology</h5>
                                            </div>
                                            <ul class="list-group">
                                               <li class="list-group-item d-flex justify-content-between align-items-center">
                                                    Spotlight
                                                  {% if room.features.spotlight == 1 %}
                                                      <span><i class="far fa-check-circle"></i></span>
                                                    {% else %}
                                                    <span><i class="far fa-times-circle"></i></span>
                                                    {% endif %}
                                                </li>
                                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                                    Sound System
                                                  {% if room.features.sound_system == 1 %}
                                                      <span><i class="far fa-check-circle"></i></span>
                                                    {% else %}
                                                    <span><i class="far fa-times-circle"></i></span>
                                                    {% endif %}
                                                </li>
                                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                                    Video Conference Equipament
                                                  {% if room.features.videoConference_equipament == 1 %}
                                                      <span><i class="far fa-check-circle"></i></span>
                                                    {% else %}
                                                    <span><i class="far fa-times-circle"></i></span>
                                                    {% endif %}
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="row"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class=" col-4 align-content-md-center pt-5 pb-5">

                <h3 class=" text-primary pt-5">Bookings</h3>
                <div id="calendar" class="pb-5"></div>

                <input type="hidden" id="valueRoom" value="{{ room.id }}">
                <h3 class=" text-primary">Complete your booking</h3>

                <form method="post" novalidate >
                    {% csrf_token %}
                   {% include 'includes/bootstrap_form.html' with form=form %}
                    <button type="submit" class="btn btn-primary text-left" value="submit">Reservate</button>
                </form>

            </div>

        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'js/calendarRoom.js' %}"></script>
{% endblock %}

templates/search.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="border border-right">
                <div class="container-fluid w-100 mb-4 p-2" style="background-color: #6c757d">
                    <p class="h6">mostrando <strong>{{ rooms.count }}</strong> salas disponibles el:
                        <strong>{{ date }}</strong></p>
                </div>
                {% for room in rooms %}
                    <div class="col">
                        <div class="card" style="width: 18rem;">
                            <img class="card-img-top" src="{% static 'media/8-sala-de-conferencias-in-zalacain.jpg' %}" alt="Card image cap">
                            <div class="card-body">
                                <h5 class="card-title">{{ room.name }}</h5>
                                <p class="card-text">{{ room.features }}</p>
                                <a href="#" id="search-reservate"  class="btn btn-primary">Reservate</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col">
                <div class="position-fixed" id="reservate">
                    adios
                    El término wikinota 1​ (del hawaiano wiki, «rápido»)2​ alude al nombre que recibe un sitio web,
                    cuyas páginas pueden ser editadas directamente desde el navegador, donde los mismos usuarios crean,
                    modifican o eliminan contenidos que, generalmente, comparten. No tiene por qué ser necesariamente un
                    sitio en la web, puesto que hay wikis instalables para uso en el escritorio de un computador
                    personal o que pueden portarse en un llavero USB que lleven un entorno LAMP, como por ejemplo XAMPP.

                    Los textos o «páginas wiki» tienen títulos únicos. Si se escribe el título de una página wiki en
                    algún sitio de la wiki entre dobles corchetes ([[Título de la página]]), esta palabra se convierte
                    en un «enlace web» a la página correspondiente. De este modo, en una página sobre «alpinismo» puede
                    haber una palabra como «piolet» o «brújula» que esté marcada como palabra perteneciente a un título
                    de página wiki. La mayor parte de las implementaciones de wikis indican en el localizador de
                    recursos uniforme (URL) de la página el propio título de la página wiki (en Wikipedia, ocurre así:
                    //es.wikipedia.org/wiki/Alpinismo> es el URL de la página wiki Alpinismo), lo que facilita el uso y
                    la aplicación general del enlace fuera del propio sitio web. Además, esto permite formar en muchas
                    ocasiones una coherencia terminológica, y genera una ordenación natural del contenido.

                    Su principal tarea, a la que le debe su fama hasta el momento, ha sido la creación de enciclopedias
                    colectivas, género al que pertenece Wikipedia. Existen muchas otras aplicaciones más cercanas a la
                    coordinación de informaciones y acciones, o la puesta en común de conocimientos o textos dentro de
                    grupos.


                </div>

            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'js/callsAsync.js' %}"></script>
{% endblock %}